#ifndef _COMM_PATCHER_H
#define _COMM_PATCHER_H

//#define DEFAULT_UPDATESERVER_PORT	6994

#define NUM_VALID_UPDATESERVER_PORTS 3
extern int valid_updateserver_ports[NUM_VALID_UPDATESERVER_PORTS];
#define DEFAULT_PATCHSERVER_LISTEN_PORT 6993

#endif

#define XFER_BLOCK_SIZE 16384
#define PATCHER_PROTOCOL_OLD_VERSION 20040407 // last protocol version before PC-Mac split
#define PATCHER_PROTOCOL_VERSION 20081120     // date protocol last changed

#include "netio.h"

enum
{
	PATCHSERVER_NEW_CLIENT = COMM_MAX_CMD,
	PATCHSERVER_CLIENT_OK,
	PATCHSERVER_PATCH,
	PATCHSERVER_FULL_MANIFEST,
	PATCHSERVER_UP_TO_DATE,
	PATCHSERVER_ERROR_MSG,
	PATCHSERVER_DATA,
	PATCHSERVER_PROJECT_LIST,
	PATCHSERVER_DISCONNECTED,
	PATCHSERVER_SEND_FILES,
	PATCHSERVER_SEND_FILE_PART,
	PATCHSERVER_REGKEYS,
	PATCHSERVER_FULL_MANIFEST_COMING,
	PATCHSERVER_CONNECT_STATUS,
	PATCHSERVER_SMALLEST_DIFF,
	PATCHSERVER_IMAGE_CHECKSUM,
	PATCHSERVER_NEW_CLIENT_MULTIFILE,
	PATCHSERVER_CIDER_UPDATE,
	PATCHSERVER_SEND_UPDATER_FILE_PART
};

enum
{
	PATCHCLIENT_REQ_NEW_CLIENT = COMM_MAX_CMD,
	PATCHCLIENT_MANIFEST,
	PATCHCLIENT_REQ_FILES,
	PATCHCLIENT_REQ_FILE_PART,
	PATCHCLIENT_REQ_DATA,
	PATCHCLIENT_REQ_PROJECT_LIST,
	PATCHCLIENT_CONNECT,
	PATCHCLIENT_REQ_SMALLEST_DIFF,
	PATCHCLIENT_REQ_MAJOR_PATCH,
	PATCHCLIENT_BADFILES,
	PATCHCLIENT_REQ_IMAGE_CHECKSUM,
	PATCHCLIENT_FATAL_ERROR,
	PATCHCLIENT_REQ_NEW_CLIENT_MULTIFILE,
	PATCHCLIENT_REQ_CIDER_UPDATE,
	PATCHCLIENT_REQ_UPDATER_FILE_PART
};

