
#ifndef _FXLISTS_H
#define _FXLISTS_H

typedef S64 FxHandle;

// Generated by mkproto
void* hdlGetPtrFromHandle(FxHandle fxid);
FxHandle hdlGetHandleFromPtr(void* ptr, FxHandle handle);
FxHandle hdlAssignHandle(void* ptr);
void hdlClearHandle(FxHandle fxid);
void hdlInitHandles(int initial_max_handles);
void hdlMoveHandlePtr(FxHandle tohandle, FxHandle fromhandle);
// End mkproto
#endif
