#ifndef _CONTAINER_TPLT_UTILS_H
#define _CONTAINER_TPLT_UTILS_H

#include "sql/sqlinclude.h"
#include "ContainerField.hpp"

C_DECLARATIONS_BEGIN

typedef struct StashTableImp *StashTable;
typedef const struct StashTableImp *cStashTable;

#define MAX_QUERY_SIZE 524288
#define MAX_QUERY_RESULTS 2048
#define CONTAINER_TEXT_INITIAL_SIZE 8192

typedef struct
{
	char	*field;
	char	*value;
} ContainerLine;

typedef struct
{
	char			*data;
	int				data_max;
	StashTable		hash_table;
	ContainerLine	*lines;
	int				max_lines;
	int				count;
} IndexedContainer;

typedef struct
{
	char	*buf;
	int		table_idx;
	int		last_table_idx;
	char	*idx_name;
	char	*table;
	char	*field;
	char	*value;
	char	*curr;
	char	last_table[128];
	char	*args[100];
	int		count;
} CtnrLineState;

typedef enum DatabaseProvider {
	DBPROV_UNKNOWN=0,
	DBPROV_MSSQL,
	DBPROV_POSTGRESQL,
	DBPROV_COUNT
} DatabaseProvider;

#define DBPROV_XDEFAULT() xdefault: FatalErrorf(__FUNCTION__ " not implemented for database provider %d", gDatabaseProvider)

// Generated by mkproto
char *findFieldText(char *data,char *field,char *buf);
void containerInitIndex(IndexedContainer *cont_lines,const char *data,int create);
void containerFreeIndex(IndexedContainer *cont);
int isNumber(char *s);
int valueNotNull(char *s);
int ctnrLineGet(CtnrLineState *state);
void ctnrLineInit(CtnrLineState *state,char *data,char *table_name);
void cntrLineFree(CtnrLineState *state);
void setFieldRequiresCR(int yes);
void checkEntCorrupted(char *data);

#ifdef DBSERVER
#define FLUSH_BINDS 1500 // Needs to be below the SQL Native Client 10 limit of 2100
void bindInputParameter(HSTMT stmt, int index, ContainerFieldType type, const void * data, SQLLEN * size);
void bindOutputColumn(HSTMT stmt, int index, ContainerFieldType type, size_t size, void * data, SQLLEN * rows);
#endif

C_DECLARATIONS_END

// End mkproto
#endif
