#ifndef _CONTAINER_TPLT_UTILS_H
#define _CONTAINER_TPLT_UTILS_H

#include "sql/sqlinclude.h"

C_DECLARATIONS_BEGIN

typedef struct StashTableImp *StashTable;
typedef const struct StashTableImp *cStashTable;

#define MAX_QUERY_SIZE 524288
#define MAX_QUERY_RESULTS 2048
#define CONTAINER_TEXT_INITIAL_SIZE 8192

typedef enum ContainerFieldType
{
	CFTYPE_NULL,

	// Unquoted types
	CFTYPE_BYTE,
	CFTYPE_SHORT,
	CFTYPE_INT,
	CFTYPE_FLOAT,

	// Quoted types
	CFTYPE_STRING,
	CFTYPE_WSTRING,
	CFTYPE_DATETIME,
	CFTYPE_DATETIME_TIMEZONE,
	CFTYPE_BINARY,

	CFTYPE_COUNT
} ContainerFieldType;

#define CFTYPE_ANSISTRING CFTYPE_STRING
#define CFTYPE_UNICODESTRING CFTYPE_STRING
#define CFTYPE_ANSISTRING_MAX CFTYPE_STRING
#define CFTYPE_UNICODESTRING_MAX CFTYPE_STRING

#define FIRST_QUOTED_TYPE CFTYPE_UNICODESTRING

#define CFTYPE_IS_ARRAY(_e) ((_e) == CFTYPE_UNICODESTRING || (_e) == CFTYPE_ANSISTRING)
#define CFTYPE_IS_LEGACY(_e) false
#define CFTYPE_IS_DYNAMIC(_e) ((_e) == CFTYPE_BINARY || (_e) == CFTYPE_UNICODESTRING_MAX || (_e) == CFTYPE_ANSISTRING_MAX || CFTYPE_IS_LEGACY(_e))
#define CFTYPE_IS_UNBOUNDABLE(_e) ((_e) == CFTYPE_STRING || (_e) == CFTYPE_BINARY)
#define CFTYPE_IS_BOUND(_e, _cs) ((_cs) > 0 || !CFTYPE_IS_UNBOUNDABLE(_e))

typedef struct
{
	char	*field;
	char	*value;
} ContainerLine;

typedef struct
{
	char			*data;
	int				data_max;
	StashTable		hash_table;
	ContainerLine	*lines;
	int				max_lines;
	int				count;
} IndexedContainer;

typedef struct
{
	char	*buf;
	int		table_idx;
	int		last_table_idx;
	char	*idx_name;
	char	*table;
	char	*field;
	char	*value;
	char	*curr;
	char	last_table[128];
	char	*args[100];
	int		count;
} CtnrLineState;

typedef struct ContainerFieldInfo
{
	int access_size;
	int access_type;
	int actual_type;
	int actual_type_long;
	char* db_bound_type;
	char* db_unbound_type;
} ContainerFieldInfo;

typedef enum DatabaseProvider {
	DBPROV_UNKNOWN=0,
	DBPROV_MSSQL,
	DBPROV_POSTGRESQL,
	DBPROV_COUNT
} DatabaseProvider;

#define DBPROV_XDEFAULT() xdefault: FatalErrorf(__FUNCTION__ " not implemented for database provider %d", gDatabaseProvider)

// Generated by mkproto
char *findFieldText(char *data,char *field,char *buf);
int dataType(char *str, int *column_size, int *num_bytes, char **type_name);
void containerInitIndex(IndexedContainer *cont_lines,const char *data,int create);
void containerFreeIndex(IndexedContainer *cont);
int isNumber(char *s);
int valueNotNull(char *s);
int ctnrLineGet(CtnrLineState *state);
void ctnrLineInit(CtnrLineState *state,char *data,char *table_name);
void cntrLineFree(CtnrLineState *state);
void setFieldRequiresCR(int yes);
void checkEntCorrupted(char *data);

#ifdef DBSERVER
#define FLUSH_BINDS 1500 // Needs to be below the SQL Native Client 10 limit of 2100
void odbcInitialSetup(void);
void queryDatabaseVersion(void);
void bindInputParameter(HSTMT stmt, int index, enum ContainerFieldType type, const void * data, SQLLEN * size);
void bindOutputColumn(HSTMT stmt, int index, enum ContainerFieldType type, size_t size, void * data, SQLLEN * rows);
#endif

C_DECLARATIONS_END

// End mkproto
#endif
