[CmdletBinding()]
param(
    [ValidateSet('Status', 'StaticProof', 'RestBasisFrame20', 'RestBasisBottom', 'RestBasisBottomFrame', 'FullFrame30', 'FullFrame', 'Tracked')]
    [string]$Variant = 'Status',
    [ValidateRange(1, 60)]
    [int]$FrameStart = 1
)

# Stages one of the issue-36 forensic canary audition variants into the
# runtime canary include (bin/data/sequencers/cohsourcedev_canary.inc).
# The installer must already have installed canary mode (-IncludeCanary);
# this script never touches tracked data files and 'Tracked' restores the
# original tracked bytes.

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$runtimeCanaryInclude = Join-Path $repoRoot 'bin\data\sequencers\cohsourcedev_canary.inc'
$trackedCanaryInclude = Join-Path $repoRoot 'agent\animation\canary-sequencer.inc'
$variants = @{
    StaticProof = Join-Path $repoRoot 'agent\animation\canary-static-proof.inc'
    RestBasisFrame20 = Join-Path $repoRoot 'agent\animation\canary-rest-basis-frame20.inc'
    RestBasisBottom = Join-Path $repoRoot 'agent\animation\canary-rest-basis-bottom.inc'
    FullFrame30 = Join-Path $repoRoot 'agent\animation\canary-full-frame30.inc'
}

function Get-Sha256([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return $null }
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
        return ([System.BitConverter]::ToString($sha256.ComputeHash([System.IO.File]::ReadAllBytes($Path)))).Replace('-', '').ToLowerInvariant()
    }
    finally {
        $sha256.Dispose()
    }
}

if ($Variant -eq 'Status') {
    [pscustomobject]@{
        runtimePresent = (Test-Path -LiteralPath $runtimeCanaryInclude -PathType Leaf)
        runtimeSha256 = Get-Sha256 $runtimeCanaryInclude
        trackedSha256 = Get-Sha256 $trackedCanaryInclude
        staticProofSha256 = Get-Sha256 $variants.StaticProof
        restBasisFrame20Sha256 = Get-Sha256 $variants.RestBasisFrame20
        restBasisBottomSha256 = Get-Sha256 $variants.RestBasisBottom
        fullFrame30Sha256 = Get-Sha256 $variants.FullFrame30
        staged = if (Test-Path -LiteralPath $runtimeCanaryInclude -PathType Leaf) {
            $h = Get-Sha256 $runtimeCanaryInclude
            if ($h -eq (Get-Sha256 $variants.StaticProof)) { 'StaticProof' }
            elseif ($h -eq (Get-Sha256 $variants.RestBasisFrame20)) { 'RestBasisFrame20' }
            elseif ($h -eq (Get-Sha256 $variants.RestBasisBottom)) { 'RestBasisBottom' }
            elseif ($h -eq (Get-Sha256 $variants.FullFrame30)) { 'FullFrame30' }
            elseif ($h -eq (Get-Sha256 $trackedCanaryInclude)) { 'Tracked' }
            else { 'Unknown' }
        } else { 'Missing' }
    } | ConvertTo-Json
    exit 0
}

if (-not (Test-Path -LiteralPath $runtimeCanaryInclude -PathType Leaf)) {
    throw "Runtime canary include is missing; install canary mode first: agent/install-webswing-animation.ps1 -Action Install -IncludeCanary"
}

$generated = $false
if ($Variant -in @('FullFrame', 'RestBasisBottomFrame')) {
    if ($Variant -eq 'RestBasisBottomFrame' -and $FrameStart -gt 5) {
        throw 'RestBasisBottomFrame requires FrameStart 1..5.'
    }
    if ($Variant -eq 'FullFrame' -and $FrameStart -ge 60) {
        throw 'FullFrame requires FrameStart 1..59 so the Anim range has an end frame.'
    }
    $endFrame = $FrameStart + 1
    $asset = if ($Variant -eq 'RestBasisBottomFrame') {
        'MALE/COHSOURCEDEV_RETARGET_RESTBASIS_BOTTOM'
    } else {
        'MALE/COHSOURCEDEV_RETARGET_SWING_FULL'
    }
    $content = @"
// Issue 36 forensic canary: one frozen source frame from an isolated proof clip.
// Generated by agent/stage-issue36-canary.ps1; never a production sequencer move.

Move COHSOURCEDEV_CUSTOM_CANARY
	Interpolate 5
	Priority 50
	Scale 0
	Type Male
		Anim $asset $FrameStart $endFrame
		TEnd
	Member "<COHSOURCEDEV_CUSTOM_CANARY>", "<DEATHIRQ>", "<HITIRQ>", "<REACTIRQ>", "<BLOCKIRQ>", "<BLOCK>", "<STUNMOVE>", "<ATTACKIRQ>", "<MOVEIRQ>"
	Interrupts "<COHSOURCEDEV_CUSTOM_CANARY>", "<JUMPS>", "<FALL>", "<GROUNDMOVEALL>", "<READY>", "<FLYREADY>"
	Requires COHSOURCEDEV_ANIMCANARY
	Flags Cycle
MEnd
"@
    [System.IO.File]::WriteAllText($runtimeCanaryInclude, $content, [System.Text.UTF8Encoding]::new($false))
    $generated = $true
} else {
    $source = if ($Variant -eq 'Tracked') { $trackedCanaryInclude } else { $variants[$Variant] }
    Copy-Item -LiteralPath $source -Destination $runtimeCanaryInclude -Force
}
[pscustomobject]@{
    staged = $Variant
    frameStart = if ($generated) { $FrameStart } else { $null }
    frameEnd = if ($generated) { $FrameStart + 1 } else { $null }
    source = if ($generated) { 'generated-in-memory' } else { $source }
    runtimeSha256 = Get-Sha256 $runtimeCanaryInclude
} | ConvertTo-Json
